### ISSUE TITLE
nicer urls...

### ISSUE THREAD

**Issue by jedie** [hovel/pybbm#20]
Idea to create a little bit nicer urls: Add a slug after the ID (but doesn't use it) e.g.:

http://pybbm.org/forum/1/ -> http://pybbm.org/forum/1/PyBBM-Features/
http://pybbm.org/topic/1/ -> http://pybbm.org/topic/1/What-do-you-want-to-see-in-next-release/

Any interests in this? The i would be fork and try to create a pull request...

**Comment by emilian** [comment]
+1 For nicer URLs.

**Comment by DylannCordel** [comment]
:+1:

@zeus : I think we can have multiple forums with same slug. e.g : forums called "Misc" in various categories. e.g :

* Category "Public area"
    * Category "Languages"
        * Forum "Python"
        * Forum "Misc"
    * Category "Coolest animals"
        * Forum "Magic Ponies"
        * Forum "Mist"

To avoid this, we have two main solutions IMHO :

1. Add the id in the urls : `/forum/1,misc/` and `/forum/4,misc/
2. suffix identic slug with auto-increment (on forum creation or update) : `/forum/misc/`, `/forum/misc-2/`

I think the second is the best.

But, if we enhance pybb with nicer URLs, we should have a more meanful URLs, because `/forum/misc/` and `/forum/misc-2/` doesn't have any signification without the context (the category)
We could have a real meanful URL (better for SEO) with full or partial path :

1. partial with the slug of the parent category : `languages/misc` and `coolest-animals/misc`
2. with complete path : `public-area/languages/misc` and `public-area/coolest-animals/misc`

We could then also add topic slug : `public-area/languages/python/help-with-pip-please`.

To be able to have those URLs, we need to have a different URL format for the main "public" part : content displaying (forums lists, topics lists, posts lists). We could use :

* `^content/(?P<path>.+)/(?P<pk>\d+)/$` : PostView (this url requires to disallow numerous slugs for categories, forums and topics).
* `^content/(?P<path>.+)/$` : a new view : `ContentWrapperView` which will analyse the path, then call a CategoryView, ForumView, or TopicView.
* all other "old" urls could still exists for backward compatibility and SEO.

What do you think about it ?

**Comment by zeus** [comment]
IMHO the best way is to use full human-readable url.
e.g.: `public-area/languages/python/help-with-pip-please`

The problem that this approach require slug definition for every topic, what is nearly impossible :(
So we have next structure:
- Category slug - required
- Forum slug - required
- topic slug - optional
- post slug (for super nice direct-to-post url) - optional

Now we have cool urls like:
`^(?P<category_slug>.+)/(?P<forum_slug>.+)/(?P<topic_slug_or_pk>.+)`

This can be:
- `/languages/python/pybbm` if topic slug is defined
- `/languages/python/234` if topic slug is not defined

For simplification we can set slug for topic equal to pk if slug is empy (and convert current database same way for categories and slugs).

Old url scheme should be able to run in two ways (switchable by admin):
- Redirect to new url
- Work as it works now

**Comment by DylannCordel** [comment]
Slug for topic should not be a problem : a topic must have a subject, so we can slugify it and add an auto-increment if there is already a topic with that slug (e.g : `my-topic`, `my-topic-1`, `my-topic-2` etc.)

URL you suggest does not contain sub-categories or sub-forums. (e.g : `cat-parent/cat-child/forum-parent/forum-child/topic`) I think it's ok : forums with sub-categories and/or sub-forums are not so common.

I'm not a big fan of adding a new input in the topic form to specify the slug. We could have a setting to let users managing slugs themselves or not.

**Comment by basilelegal** [comment]
Issue nearly done, I just need to check few details when I'll have time. But it should be ready next week.

**Comment by emilian** [comment]
Awesome. Can't wait to see it.

**Comment by emilian** [comment]
Any update on the nicer urls @basilelegal ?

**Comment by basilelegal** [comment]
I did the pull request last week @emilian https://github.com/hovel/pybbm/pull/180.

**Comment by emilian** [comment]
Thanks. It worked!

I would remove the /contents/ prefix since it creates long URLs. 

Also, if you get the following error: `TypeError: __init__() got an unexpected keyword argument 'preserve_default'` you will need to upgrade Django to 1.7.1 to fix it.

**Comment by DylannCordel** [comment]
Hi @emilian

About `TypeError`, a correction will be added (see [this note](https://github.com/hovel/pybbm/pull/180/files#r31447317)) to avoid `TypeError` Exception with Django 1.7.0.

About `contents/` prefix, if you remove it, you risk collisions of URLs for all categories with a slug matching a pybb url. If your think that `contents/` prefix is really disgraceful and want to remove it, we have to blacklist those categories slugs:

* feeds
* category
* users
* forum
* block_user
* unblock_user
* profile
* topic
* post
* subscription
* api
* mark_all_as_read

Doing this mean to keep this blacklist uptodate when we update pybb urls.

I have no preference. @GeyseR, @zeus : what is your opinon ?

**Comment by emilian** [comment]
My forum is installed in a "directory" called forum so having another prefix called `contents` just did not make sense.  I don't think the collision will be a problem so I went ahead and removed the prefix.

A way to blacklist the slugs would probably be best just so that forum owners aren't going to run into any problems with the URLs.

**Comment by GeyseR** [comment]
Hi guys!
Personally I prefer explicit prefix to exclude collisions with other pybbm urls. But we can cut this prefix to one letter, "c" for example.
I have some doubts on implementation details, but whole solution looks good for me. I will submit comments or new fixed pull request soon :)

**Comment by DylannCordel** [comment]
@jedie or @lampslave : could you close this issue now it's merged ?
