### ISSUE TITLE
Why banned users are still logged in?

### ISSUE THREAD

**Issue by lampslave** [hovel/pybbm#268]
There is no force logout in `views.block_user`.

**Comment by DylannCordel** [comment]
We could add a Middleware for this, but is this in the scope of pybb ?

```python
from django.contrib.auth import logout

class LogoutBannedUserMiddleware(object):
    def process_request(self, request):
        if request.user.is_authenticated() and not request.user.is_active:
            logout(request)

```

**Comment by lampslave** [comment]
Instead of middleware we can add `logout` to `views.block_user`, I just wonder why this wasn't done before...

**Comment by DylannCordel** [comment]
We can't : this view is called with an admin user, not the user which is banned. If we call logout in this view, it's the admin who will be logged out because logout need the request to manipulate the user's session. See [django.contrib.auth.logout](https://github.com/django/django/blob/master/django/contrib/auth/__init__.py#L159)

**Comment by lampslave** [comment]
Yes, you're right. Then this isn't pybbm issue. Maybe https://django-force-logout.readthedocs.io/ will be helpful.
